apiVersion: v1
kind: ReplicationController
metadata:
  name: rp-test
  labels:
    app: web-server
    type: webservers
spec:
  template:

    metadata:
     name: myapp-prod
     labels:
       app: web-server
       type: webservers
    spec:
      containers:
      - name: jenkins
        image: jenkins:latest

  replicas: 3
